### PR TITLE
use protobuf content type instead of json for k8s client

### PR DESCRIPTION
**Pull request by bhavi-koduru**
**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

This MR is a part of effort to elevate single eks cluster performance by migrating the EKS components to use protobuf instead of json.

Modify kubeconfig type to use content type application/vnd.kubernetes.protobuf instead of json for performance gain.

**If an issue # is not available please add steps to reproduce and the controller logs**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this PR introduce any new dependencies?**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this PR introduce any user-facing change?**:

No
```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by yash97 — APPROVED** [review]
lgtm 🚀

**Review by hakuna-matatah — COMMENTED** [review]
/lgtm

**Review by hakuna-matatah — APPROVED** [review]

**Review by mengqiy — APPROVED** [review]
/lgtm

**Comment by yash97** [comment]
Apparently api server does not fall back if type does not support CRD. Here is issue in k/k https://github.com/kubernetes/kubernetes/issues/86253.

**Review by jaydeokar — APPROVED** [review]
lgtm

**Pull request merged**
